@snap_backend_HostAddress = http://localhost:5004

POST {{snap_backend_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "FirstName": "Filip",
  "LastName": "Tejic",
  "Email": "admin@snap.com",
  "Password": "admin"
}

###

POST {{snap_backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "Email": "markovic@example.com",
  "Password": "password"
}